from os import system
import cx_Oracle
con = cx_Oracle.connect("scott/tiger")
def mainmenu():
    print("..Welcome in Emp Table..")
    print("1. For Enter the data")
    print("2. For Read the data acc. to ID Number")
    print("3. For Update the data")
    print("4. For Delete the data")
    print("5. Exit")
    ch = eval(input("Enter the choice:"))
    if ch == 1:
        enter()
    elif ch == 5:
        exit()
    elif ch == 2:
        read()
    elif ch == 3:
        upda()
    elif ch == 4:
        delet()
    else:
        print("Invalid Input....")
        exit()
def enter():
    cur = con.cursor()
    id = eval(input("Enter the ID: "))
    name = input("Enter the name: ")
    job = input("Enter the job: ")
    mgrr = input("Enter MGR no.: ")
    hireda = input("Enter Hire Date (format DD-MMM-YY): ")
    sal = eval(input("Enter the Salary: "))
    comm = eval(input("Enter the commission: "))
    dept = eval(input("Enter the department No. : "))
    cur.execute("insert into emp values(:id,:name,:job,:mgrr,:hireda,:sal,:comm,:dept)",{":id":id,":name":name,":job":job,":mgrr":mgrr,":hireda":hireda,":sal":sal,":comm":comm,":dept":dept})
    print("Value Inserted..")
    con.commit();
    input()
    cur.close()
    system('cls')
    mainmenu()
def read():
    cur = con.cursor()
    id = eval(input("Enter the ID for search employee data: "))
    cur.execute("select * from emp where empno =:id",{":id":id})
    t = cur.fetchall()
    print("ID= ",t[0][0])
    print("Name ",t[0][1])
    print("Job= ",t[0][2])
    print("MGR= ",t[0][3])
    date1 = t[0][4].strftime("%d-%b-%Y")
    print("Hiredate= ",date1)
    print("Salary= ",t[0][5])
    print("Commission= ",t[0][6])
    print("Department= ",t[0][7])
    input()
    cur.close()
    system('cls')
    mainmenu()
def upda():
    cur = con.cursor()
    id = eval(input("Enter Id of employee for update the data:"))
    print("Enter 1 for name updation.")
    print("Enter 2 for job updation.")
    print("Enter 3 for Salary updation.")
    ch = eval(input("Enter your Choice: "))
    if ch == 1:
        name1 = input("Enter updated name: ")
        cur.execute("update emp set ename=:name1 where empno=:id",{":name1":name1,":id":id})
        print("Updation Successful")
        con.commit()
    elif ch == 2:
        job1 = input("Enter updated job: ")
        cur.execute("update emp set job=:job1 where empno=:id",{":job1":job1,":id":id})
        print("Updation Successful")
        con.commit()
    elif ch == 3:
        sal1 = input("Enter updated Salary: ")
        cur.execute("update emp set sal=:sal1 where empno=:id",{":sal1":sal1,":id":id})
        print("Updation Successful")
        con.commit()
    else:
        print("Invalid Input...")
        exit()
    input()
    cur.close()
    system('cls')
    mainmenu()
def delet():
    id = eval(input("Enter the ID of Employee to delete record: "))
    cur = con.cursor()
    cur.execute("delete from emp where empno = :id",{":id":id})
    print("DELETION SUCCESSFUL")
    con.commit()
    input()
    cur.close()
    system('cls')
    mainmenu()
mainmenu()
con.close()