# f = open("abc.txt","w")
# f.write("joban\n")
# f.write("jit\n")
# f.write("singh\n")
# f.close()   
f = open("abc.txt")
# # s=f.read()
# # count=0
# # for i in s:
# #     if i!="\n" and i!=" ":
# #         count+=1
# # print(type(s))
# # print(s)
# # print(count)
# s = f.readline()
# print(s)
# print(type(s))
# # s1 = f.readline()
# # print(s1)
# # s = f.readlines()
# # print(s)
# # print(type(s))
# f.close()
# f = open("abc.txt","a")
# f.writelines(['Ram','sham'])
f.close()