from tkinter import *
root = Tk()
def submit():
    with open("record.txt","a") as f:
        f.write(f"{namevalue.get(),classvalue.get(),rollvalue.get(),mobile.get(),payment.get(),chk.get()}\n")
    l1=Label(root,text="Form Submitted",font="rockwell 20 bold")
    l1.grid(row=9,column=1)
root.title("Student Registraton Form")
root.geometry("590x300")
heading = Label(root,text="ABC School,XYZ City",font="rockwell 15 bold",foreground="red")
msg=Label(root,text="Note: Fill this form if you have paid your fees",foreground="blue",
font="rockwell 12 italic",pady=5)
name=Label(root,text="Name:",font="rockwell 10 bold")
classes=Label(root,text="Class:",font="rockwell 10 bold")
roll=Label(root,text="Rollno:",font="rockwell 10 bold")
mobno=Label(root,text="Registed Mobile No.",font="rockwell 10 bold")
pay=Label(root,text="Mode of Payment:",font="rockwell 10 bold")
heading.grid(row=0,column=1)
msg.grid(row=1,column=1)
name.grid(row=2,column=0)
classes.grid(row=3,column=0)
roll.grid(row=4,column=0)
mobno.grid(row=5,column=0)
pay.grid(row=6,column=0)
namevalue = StringVar()
classvalue = StringVar()
rollvalue = StringVar()
mobile = StringVar()
payment = StringVar()
chk = IntVar()
namevaluechk =Entry(root,textvariable=namevalue)
classvaluechk = Entry(root,textvariable=classvalue)
rollvaluechk = Entry(root,textvariable=rollvalue)
mobilevaluechk = Entry(root,textvariable=mobile)
payment = Entry(root,textvariable=payment)
namevaluechk.grid(row=2,column=1)
classvaluechk.grid(row=3,column=1)
rollvaluechk.grid(row=4,column=1)
mobilevaluechk.grid(row=5,column=1)
payment.grid(row=6,column=1)
checkvalue = Checkbutton(root,text="Check if you receive fees receipt.",variable=chk)
checkvalue.grid(row=7,column=1)
button = Button(root,text="Submit",command=submit)
button.grid(row=8,column=1)
root.mainloop()